services:
  bot:
    image: smart-wash-bot
    container_name: smart-wash-bot
    build: .
    command: python -m app
    env_file: .env
    volumes:
      - .:/code
  nats:
    image: nats:2.10-alpine
    ports:
      - 8222:8222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
